export const LOTE_LAYOUT_SECTIONS = [
  { section_id: "principal", titulo: "Principal", ordem: 1, metadata: { is_principal: true, locked: true } },
  { section_id: "geral", titulo: "Geral", ordem: 10 },
  { section_id: "compra", titulo: "Motivo", ordem: 20 },
  { section_id: "identificacao", titulo: "Identificação", ordem: 30 },
  { section_id: "observacoes", titulo: "Observações", ordem: 40 },
  { section_id: "campos_personalizados", titulo: "Campos Personalizados", ordem: 50 }
];

export const LOTE_FIXED_FIELDS = [
  { field_name: "nome", label: "Descrição", tipo: "text", section_id: "principal", ordem: 10, obrigatorio: true, protected_required: true },
  { field_name: "ativo_visual", label: "Ativo", tipo: "status", section_id: "principal", ordem: 20, read_only: true },
  { field_name: "numero_lote", label: "Código", tipo: "readonly", section_id: "principal", ordem: 30, read_only: true },
  { field_name: "data_entrada", label: "Data de Entrada", tipo: "date", section_id: "geral", ordem: 10, obrigatorio: true, protected_required: true },
  { field_name: "setor_id", label: "Setor", tipo: "relation", section_id: "geral", ordem: 20, obrigatorio: true, protected_required: true },
  { field_name: "area_entrada_id", label: "Área de Entrada", tipo: "relation", section_id: "geral", ordem: 30, obrigatorio: true, protected_required: true },
  { field_name: "quantidade_cabecas", label: "Qtd. Cabeças", tipo: "number", section_id: "geral", ordem: 40, obrigatorio: true, protected_required: true },
  { field_name: "categoria_manejo_id", label: "Categoria de Manejo", tipo: "relation", section_id: "geral", ordem: 50, obrigatorio: true, protected_required: true },
  { field_name: "sexo", label: "Sexo", tipo: "select", section_id: "geral", ordem: 60, obrigatorio: true, protected_required: true },
  { field_name: "raca_predominante", label: "Raça Predominante", tipo: "text", section_id: "geral", ordem: 70, obrigatorio: true, protected_required: true },
  { field_name: "peso_medio_kg", label: "Peso Médio (kg)", tipo: "number", section_id: "geral", ordem: 80, obrigatorio: true, protected_required: true },
  { field_name: "idade_media_meses", label: "Idade Média (meses)", tipo: "number", section_id: "geral", ordem: 90, obrigatorio: true, protected_required: true },
  { field_name: "sistema_produtivo", label: "Sistema Produtivo", tipo: "checkbox_group", section_id: "geral", ordem: 100, obrigatorio: true, protected_required: true },
  { field_name: "motivo_entrada", label: "Motivo da Entrada", tipo: "select", section_id: "compra", ordem: 10 },
  { field_name: "fornecedor_id", label: "Fornecedor", tipo: "relation", section_id: "compra", ordem: 20, conditional_required: "motivo_entrada:Compra" },
  { field_name: "cidade_origem", label: "Cidade Origem", tipo: "text", section_id: "compra", ordem: 30, conditional_required: "motivo_entrada:Compra" },
  { field_name: "estado_origem", label: "Estado Origem", tipo: "text", section_id: "compra", ordem: 40, conditional_required: "motivo_entrada:Compra" },
  { field_name: "nota_fiscal", label: "Nota Fiscal", tipo: "text", section_id: "compra", ordem: 50, conditional_required: "motivo_entrada:Compra" },
  { field_name: "chave_nfe", label: "Chave NF-e", tipo: "text", section_id: "compra", ordem: 60, conditional_required: "motivo_entrada:Compra" },
  { field_name: "numero_gta", label: "Nº GTA", tipo: "text", section_id: "compra", ordem: 70, conditional_required: "motivo_entrada:Compra" },
  { field_name: "valor_total_compra", label: "Valor Total (R$)", tipo: "number", section_id: "compra", ordem: 80, conditional_required: "motivo_entrada:Compra" },
  { field_name: "valor_por_cabeca", label: "Valor p/ Cabeça (R$)", tipo: "readonly", section_id: "compra", ordem: 90, conditional_required: "motivo_entrada:Compra", read_only: true },
  { field_name: "valor_frete", label: "Valor Frete (R$)", tipo: "number", section_id: "compra", ordem: 100, conditional_required: "motivo_entrada:Compra" },
  { field_name: "motivo_ajuste", label: "Motivo do Ajuste", tipo: "textarea", section_id: "compra", ordem: 110, conditional_required: "motivo_entrada:Ajuste" },
  { field_name: "motivo_outros", label: "Motivo", tipo: "textarea", section_id: "compra", ordem: 120, conditional_required: "motivo_entrada:Outros" },
  { field_name: "identificador_nome", label: "Identificador (Nome)", tipo: "text", section_id: "identificacao", ordem: 10 },
  { field_name: "identificador_sigla", label: "Identificador (Sigla)", tipo: "text", section_id: "identificacao", ordem: 20 },
  { field_name: "identificador_cor", label: "Identificador (Cor)", tipo: "select", section_id: "identificacao", ordem: 30 },
  { field_name: "observacoes", label: "Observações", tipo: "textarea", section_id: "observacoes", ordem: 10 }
];